M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-01-13T16:26:26+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-13T16:26:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
%
G90
G05
T1
X130.71Y-112.25
X133.25Y-112.25
M30
